see if file exists, docker load too

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -40,12 +40,16 @@ jobs:
         run: echo "::set-output name=build_id::$(nix build --json | jq -r '.[].outputs | to_entries[].value')"
       - name: Try to log
         run: echo "${{ steps.build_step.outputs.build_id }}"
+      - name: Try to find
+        run: echo "$([[ -e ${{ steps.build_step.outputs.build_id }} ]] && echo "File exist" || echo "File not found")"
       - name: Log in to the Container registry
         uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
         with:
           registry: ${{ env.REGISTRY }}
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
+      - name: Docker Load
+        run: docker load ${{ steps.build_step.outputs.build_id }}
   publish:
     needs: build
     runs-on: ubuntu-latest
@@ -55,6 +59,8 @@ jobs:
     steps:
       - name: Try to log
         run: echo "${{ needs.build.outputs.build_id }}"
+      - name: Try to find
+        run: echo "$([[ -e ${{ needs.build.outputs.build_id }} ]] && echo "File exist" || echo "File not found")"
       # - name: Upload image
       #   uses: actions/upload-artifact@v3
       #   with:
